apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bq-eviction-policy
  namespace: eviction
  labels:
    app: eviction
    component: bq-eviction-policy
spec:
  schedule: "0 */3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command: ["/bin/bash","-c"]
            args: ["python2 /eviction/eviction.py"]
            name: bq-eviction-policy
            image: us.gcr.io/newscorp-newsid-prod/bq-eviction-policy:latest
            volumeMounts:
            - name: eviction-gcp
              mountPath: "/secrets/gcp"
              readOnly: true
            - name: bq-eviction-policy
              mountPath: /eviction/eviction.yml
              subPath: eviction.yml 
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secrets/gcp/credentials.json"
            - name: NEWSID_GCP_PROJECT
              value: "newscorp-newsid-prod"
            - name: NEWSID_ENV
              value: "prod"
            - name: NEWSID_GCP_EVICTION_LOG_LOCATION
              value: "/eviction/logs"
            - name: NEWSID_GCP_EVICTION_POLICY_LOCATION
              value: "/eviction/policies"
            - name: NEWSID_GCP_EVICTION_STATUS_LOCATION
              value: "/eviction/logs"
            - name: NEWSID_GCP_BQ_DOWNSTREAM_BUFFER
              value: "3"
            - name: NEWSID_BQ_EVICTION_DRY_RUN
              value: "True"
          restartPolicy: OnFailure
          volumes:
          - name: eviction-gcp
            secret:
              secretName: eviction-gcp
          - name: bq-eviction-policy
            configMap:
              name: bq-eviction-policy-configmap
