apiVersion: v1
kind: Namespace
metadata:
  name: eviction

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: bq-eviction-policy-configmap
  namespace: eviction
data:
  eviction.yml: |-
    newsid_prod:
        good_events_dev: delete_and_evict:daily@140
