apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: collector-hpa
  namespace: snowplow
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: snowplow-collector
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: External
    external:
      metric:
        name: "loadbalancing.googleapis.com|https|request_count"
        selector:
          matchLabels:
            resource.labels.forwarding_rule_name: k8s2-fs-i83eemfn-snowplow-newsid-prod-collector-ingres-rbf6mayp
      target:
        type: AverageValue
        averageValue: 1000