apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: stream-loader-hpa
  namespace: snowplow
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: snowplow-stream-loader
  minReplicas: 3
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
